Bookstore: connect to API
Mukumbuta/Bookstore pull request #4
Opened 2022-10-01 15:47 UTC by Mukumbuta

### Feature implemented:
- Used [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) with` async/await` to make API calls.
- Fetched book list from Bookstore API on Books page load.
- Dispatched another action that passed API response to reducer and updates the state.
- Refactored the `add book` and `remove book` features to persist your changes in the server.

- Add book and remove book works in the same way after the refactor.

2022-10-01 16:47 UTC, fobadara requested changes
Hi @Mukumbuta, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ Linters are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

[OPTIONAL] You. don't need to add bookstore/  to your branch name. Just name it after a feature or action in the project.

[OPTIONAL] Kindly ensure that your commit messages are I the imperative and start with uppercase

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-01 16:47 UTC, fobadara commented on src/redux/books/book.js
> +});
[REQUIRED] Your addBook is not functioning properly.  It only displays a button unless we refresh.

|Your Bookstore|
|-----------------|
|![bookstore1](https://user-images.githubusercontent.com/62938735/193419505-eaac0ece-280f-4e21-a862-bf8e174e06e2.gif)|

2022-10-01 16:47 UTC, fobadara commented on src/redux/configureStore.js
> +import thunk from 'redux-thunk';
[REQUIRED] You should be using createAsyncThunk from the Redux toolkit

2022-10-08 19:10 UTC, vickymarz approved these changes
Hi @Mukumbuta, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-08 20:43 UTC, merged